version: "3.8"
services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www
    networks:
      - internal
    depends_on:
      - nginx
  nginx:
    image: nginx:1.25.2
    container_name: nginx
    ports:
      - "80:80"
      - "8000:8000"
      - "443:443"
    volumes:
        - ./src:/var/www
        - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - internal
networks:
  internal:
    driver: bridge
